language: node_js
node_js:
  - 'stable'
  - '8'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  # - yarn lint
  - yarn test
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $RESIN_DEPLOY_KEY > mastersKey
  - chmod 0600 mastersKey
  - ssh-add ./mastersKey
  - cat resinkey >> ~/.ssh/known_hosts
  - git remote add resin gh_ptlm500@git.resin.io:gh_ptlm500/mastersproject.git
  - git push resin master